export interface Product {
  id: number;
  name: string;
  category: string;
  price: number;
  minOrder: number;
  unit: string;
  description: string;
  image: string;
  inStock: boolean;
  discount?: number;
}

export const categories = [
  "الكل",
  "أدوات مطبخ",
  "تنظيف ونظافة",
  "أدوات حمام",
  "تخزين وتنظيم",
  "أدوات منزلية متنوعة",
];

export const products: Product[] = [
  {
    id: 1,
    name: "طقم أواني طبخ 12 قطعة",
    category: "أدوات مطبخ",
    price: 850,
    minOrder: 6,
    unit: "طقم",
    description: "طقم أواني طبخ من الستانلس ستيل عالي الجودة، مناسب للاستخدام اليومي",
    image: "🍳",
    inStock: true,
    discount: 10,
  },
  {
    id: 2,
    name: "مكنسة كهربائية صناعية",
    category: "تنظيف ونظافة",
    price: 1200,
    minOrder: 3,
    unit: "قطعة",
    description: "مكنسة كهربائية قوية بموتور 2000 واط مناسبة للأسطح المختلفة",
    image: "🧹",
    inStock: true,
  },
  {
    id: 3,
    name: "طقم عبوات تخزين (24 قطعة)",
    category: "تخزين وتنظيم",
    price: 420,
    minOrder: 12,
    unit: "طقم",
    description: "عبوات بلاستيك شفاف محكمة الإغلاق لتخزين المواد الغذائية",
    image: "📦",
    inStock: true,
    discount: 5,
  },
  {
    id: 4,
    name: "مجموعة منظفات المنزل",
    category: "تنظيف ونظافة",
    price: 180,
    minOrder: 24,
    unit: "كرتونة",
    description: "تشكيلة من المنظفات الفعالة للمطبخ والحمام والأرضيات",
    image: "🧴",
    inStock: true,
  },
  {
    id: 5,
    name: "طقم حوض حمام وإكسسوارات",
    category: "أدوات حمام",
    price: 650,
    minOrder: 6,
    unit: "طقم",
    description: "طقم إكسسوارات حمام كامل من الستانلس ستيل المطفي",
    image: "🚿",
    inStock: false,
  },
  {
    id: 6,
    name: "خلاط كهربائي 1.5 لتر",
    category: "أدوات مطبخ",
    price: 380,
    minOrder: 10,
    unit: "قطعة",
    description: "خلاط كهربائي متعدد السرعات بسعة 1.5 لتر وموتور قوي",
    image: "🥤",
    inStock: true,
    discount: 15,
  },
  {
    id: 7,
    name: "رف حائط معدني قابل للتعديل",
    category: "تخزين وتنظيم",
    price: 290,
    minOrder: 10,
    unit: "قطعة",
    description: "رف معدني متين قابل للتعديل في الارتفاع بحمولة حتى 50 كجم",
    image: "🗄️",
    inStock: true,
  },
  {
    id: 8,
    name: "طقم أدوات تنظيف شاملة",
    category: "تنظيف ونظافة",
    price: 240,
    minOrder: 15,
    unit: "طقم",
    description: "مجموعة أدوات تنظيف شاملة تشمل مماسح وفرش وأدوات متنوعة",
    image: "🧽",
    inStock: true,
  },
  {
    id: 9,
    name: "طقم سكاكين مطبخ احترافي",
    category: "أدوات مطبخ",
    price: 520,
    minOrder: 8,
    unit: "طقم",
    description: "طقم سكاكين ألمانية الصنع من الفولاذ المقاوم للصدأ - 8 قطع",
    image: "🔪",
    inStock: true,
  },
  {
    id: 10,
    name: "سلة غسيل بلاستيك كبيرة",
    category: "أدوات منزلية متنوعة",
    price: 95,
    minOrder: 20,
    unit: "قطعة",
    description: "سلة غسيل مقاس كبير من البلاستيك المتين بمقابض مريحة",
    image: "🧺",
    inStock: true,
  },
  {
    id: 11,
    name: "مضخة مياه كهربائية صغيرة",
    category: "أدوات منزلية متنوعة",
    price: 450,
    minOrder: 5,
    unit: "قطعة",
    description: "مضخة مياه كهربائية هادئة ومتينة لنقل المياه",
    image: "💧",
    inStock: true,
    discount: 8,
  },
  {
    id: 12,
    name: "مرتبة حمام مطاط مضادة للانزلاق",
    category: "أدوات حمام",
    price: 75,
    minOrder: 30,
    unit: "قطعة",
    description: "مرتبة حمام مطاطية بتصميم شبكي لمنع الانزلاق وسهلة التنظيف",
    image: "🛁",
    inStock: true,
  },
];
